export const areaToLanguage: { [key: string]: string } ={
    Germany: 'German',
    DE: 'German',
    // German cities
    Aschaffenburg: 'German',
    Berlin: 'German',
    Bochum: 'German',
    Bonn: 'German',
    Bremen: 'German',
    Chemnitz: 'German',
    Darmstadt: 'German',
    Dresden: 'German',
    Duisburg: 'German',
    Düsseldorf: 'German',
    Essen: 'German',
    Frankfurt: 'German',
    Fürth: 'German',
    Gladbeck: 'German',
    Hamburg: 'German',
    Kassel: 'German',
    Köln: 'German',
    Leipzig: 'German',
    Magdeburg: 'German',
    Mainz: 'German',
    Mannheim: 'German',
    München: 'German',
    Nürnberg: 'German',
    Potsdam: 'German',
    Regensburg: 'German',
    Stuttgart: 'German',
    Tübingen: 'German',
    Witten: 'German',
    Wolfsburg: 'German',
    'Furtwangen im Schwarzwald': 'German',
    'Frankfurt am Main': 'German',
    // German states
    Hessen: 'German',
    Bayern: 'German',
    Sachsen: 'German',
    Niedersachsen: 'German',
    'Nordrhein-Westfalen': 'German',
    // Other german-speaking countries and cities
    CH: 'German',
    Switzerland: 'German',
    Bern: 'German',
    Zürich: 'German',
    Zurich: 'German',
    'St. Gallen': 'German',
    AT: 'German',
    Austria: 'German',
    Wien: 'German',
    Salzburg: 'German',
    Linz: 'German',
    Graz: 'German',
    Innsbruck: 'German',


    // English countries and cities
    US: 'English',
    UK: 'English',
    GB: 'English',
    'United States': 'English',
    'United Kingdom': 'English',
    'New York': 'English',
    'New Jersey': 'English',
    'Los Angeles': 'English',
    'New Orleans': 'English',
    'Huntington Beach ': 'English',
    'St. Louis ': 'English',
    Nashville: 'English',
    Brooklyn: 'English',
    Boston: 'English',
    Buffalo: 'English',
    Birmingham: 'English',
    Albany: 'English',
    Houston: 'English',
    Atlanta: 'English',
    Detroit: 'English',
    Seattle: 'English',
    Pittsburgh: 'English',
    Philadelphia: 'English',
    Portland: 'English',
    Chicago: 'English',
    Miami: 'English',
    Florida: 'English',
    Hawaii: 'English',
    Minnesota: 'English',
    California: 'English',
    CA: 'English',
    Canada: 'English',
    Toronto: 'English',
    Vancouver: 'English',
    Ottawa: 'English',
    IE: 'English',
    IS: 'English',
    Iceland: 'English',
    Reykjavík: 'English',
    England: 'English',
    London: 'English',
    Bristol: 'English',
    Belfast: 'English',
    Brighton: 'English',
    Cambridge: 'English',
    'West Yorkshire': 'English',
    Norwich: 'English',
    Ireland: 'English',
    'Northern Ireland': 'English',
    Dublin: 'English',
    Scotland: 'English',
    Edinburgh: 'English',
    AU: 'English',
    Australia: 'English',
    Sydney: 'English',
    Melbourne: 'English',
    Brisbane: 'English',
    Perth: 'English',
    Canberra: 'English',
    NZ: 'English',
    'New Zealand': 'English',
    Wellington: 'English',
    Auckland: 'English',
    IL: 'English',
    Israel: 'English',
    'Tel Aviv': 'English',


    // Other languages
    France: 'French',
    FR: 'French',
    Paris: 'French',
    Marseille: 'French',
    BE: 'French',
    Belgium: 'French',
    Italy: 'Italian',
    IT: 'Italian',
    Rome: 'Italian',
    Venice: 'Italian',
    ES: 'Spanish',
    Spain: 'Spanish',
    Madrid: 'Spanish',
    Barcelona: 'Spanish',
    MX: 'Spanish',
    Mexico: 'Spanish',
    Lima: 'Spanish',
    PR: 'Spanish',
    'Puerto Rico': 'Spanish',
    'Netherlands': 'Dutch',
    CO: 'Spanish',
    BR: 'Portuguese',
    Brazil: 'Portuguese',
    PT: 'Portuguese',
    Portugal: 'Portuguese',
    NL: 'Dutch',
    Amsterdam: 'Dutch',
    DK: 'Danish',
    Denmark: 'Danish',
    Copenhagen: 'Danish',
    Sweden: 'Swedish',
    SE: 'Swedish',
    Stockholm: 'Swedish',
    Norway: 'Norwegian',
    NO: 'Norwegian',
    Oslo: 'Norwegian',
    Finland: 'Finnish',
    FI: 'Finnish',
    Helsinki: 'Finnish',
    Japan: 'Japanese',
    JP: 'Japanese',
    Tokyo: 'Japanese',
    China: 'Chinese',
    CN: 'Chinese',
    Beijing: 'Chinese',
    HK: 'Chinese',
    'Hong Kong': 'Chinese'
  }